name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
          with:
              submodules: true
        - name: Install protoc
          uses: arduino/setup-protoc@v3
          with:
            version: "30.1"
        - name: CD back to root
          run: ls
        - name: CD to mp4decrypt
          run: cd ./vsd/mp4decrypt
        - name: Build vsd
          run: cargo build --release
        - name: CD back to root
          run: cd ..
        - name: Set up upload environment
          uses: benjlevesque/short-sha@v3.0
        - name: Upload linux build
          uses: actions/upload-artifact@v4
          with:
            name: "mp4decrypt"
            path: target/release
